apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: open-webui-nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: floppy1.k3s.maxhomelab.fi
  share: /volume2/open-webui
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
